name: Publish Frontend Docker image

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_scripts/**'
      - 'Dockerfile.collector'
      - '.github/workflows/publish-collector.yaml'

env:
  DOCKER_REGISTRY: europe-docker.pkg.dev
  DOCKER_IMAGE_NAME: lks-lz-artifacts/docker-network-clientdiversity-website/frontend

jobs:
  build-docker:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        id: gcpauth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: "true"
          workload_identity_provider: "projects/311968610280/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "artifact-deployer@lks-lz-management.iam.gserviceaccount.com"

      - name: Login to Docker registry
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.gcpauth.outputs.credentials_file_path }}"
          gcloud auth configure-docker ${{ env.DOCKER_REGISTRY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

